name: Generate Plists

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run workflow on'
        default: 'main'
        required: true

jobs:
  upload_ipas:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Upload IPAs to 'ipa' release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # 删除旧 release
          gh release delete ipa --yes || echo "No release named 'ipa' found."
          gh release delete plist --yes || echo "No release named 'plist' found."

          # 创建新 release
          gh release create ipa -t "IPAs" -n "IPA files"
          gh release create plist -t "Plists" -n "Plist files"

          # 各路径模板
          IPA_URL_BASE="https://github.com/etnAtker/ipa_sideload/releases/download/ipa"
          ITMS_URL_BASE="itms-services://?action=download-manifest&url="
          PLIST_TEMPLATE_PATH="plist_template.plist"

          RESULT_URLS=""
          
          # 遍历指定文件夹中的 ipa 文件
          for ipa in ipa/*.ipa; do
            # 重命名并上传ipa
            RANDOM_SUFFIX=$(openssl rand -hex 4)
            NEW_IPA="${ipa%.ipa}_$RANDOM_SUFFIX.ipa"
            cp "$ipa" "$NEW_IPA"
            gh release upload ipa "$NEW_IPA"

            # 解压 ipa 获取 Info.plist 文件
            unzip -q "$ipa" -d ipa_contents
            INFO_PLIST=$(find ipa_contents -path "*.app/Info.plist" | head -n 1)

            # 使用 PlistBuddy 提取包名、版本号和显示名
            BUNDLE_IDENTIFIER=$(/usr/libexec/PlistBuddy -c "Print CFBundleIdentifier" "$INFO_PLIST")
            BUNDLE_VERSION=$(/usr/libexec/PlistBuddy -c "Print CFBundleShortVersionString" "$INFO_PLIST")
            DISPLAY_NAME=$(/usr/libexec/PlistBuddy -c "Print CFBundleDisplayName" "$INFO_PLIST")
            
            # 生成 plist 文件
            PLIST_FILE="${ipa%.ipa}.plist"
            PLIST_PROXY_FILE="${ipa%.ipa}.proxy.plist"
            
            IPA_URL="$IPA_URL_BASE/$ipa"
            IPA_PROXY_URL="https://mirror.ghproxy.com/$IPA_URL"
            
            sed "s|{{IPA_URL}}|$IPA_URL|g; s|{{BUNDLE_IDENTIFIER}}|$BUNDLE_IDENTIFIER|g; s|{{BUNDLE_VERSION}}|$BUNDLE_VERSION|g; s|{{DISPLAY_NAME}}|$DISPLAY_NAME|g" "$PLIST_TEMPLATE_PATH" > "$PLIST_FILE"
            sed "s|{{IPA_URL}}|$IPA_PROXY_URL|g; s|{{BUNDLE_IDENTIFIER}}|$BUNDLE_IDENTIFIER|g; s|{{BUNDLE_VERSION}}|$BUNDLE_VERSION|g; s|{{DISPLAY_NAME}}|$DISPLAY_NAME|g" "$PLIST_TEMPLATE_PATH" > "$PLIST_PROXY_FILE"
             
            # 上传 plist 文件到 release
            gh release upload plist "$PLIST_FILE"
            gh release upload plist "$PLIST_PROXY_FILE"
            
            # 清理临时文件夹
            rm -rf ipa_contents

            # 保存结果
            RESULT_URLS+="${PLIST_FILE} \n${ITMS_URL_BASE}https://github.com/etnAtker/ipa_sideload/releases/download/plist/${PLIST_FILE} \n${ITMS_URL_BASE}https://mirror.ghproxy.com/https://github.com/etnAtker/ipa_sideload/releases/download/plist/${PLIST_PROXY_FILE}\n" 
          done

          # 输出结果至release
          echo -e "\nPlists:\n$RESULT_URLS" > plist_urls.txt
          gh release upload plist plist_urls.txt
